export default Object.freeze({
	ACCOUNT_OPTIONS: "AccountOptions",
	ACCOUNT: "Account",
	FAVORITES: "Favorites",
	LISTING_DETAILS: "ListingDetails",
	LISTINGS: "Listings",
	MAP: "Map",
	ADD_FEATURES: "AddFeatures",
	ADD_IMAGES: "AddImages",
	MY_VEHICLES: "MyVehicles",
	VEHICLES_LIST: "VehiclesList",
	NEW_VEHICLE: "NewVehicle",
	VEHICLE_LOCATION: "VehicleLocation",
	HOME: "Home",
	ADD_PRICING: "AddPricing",
	LOGIN: "Login",
	REGISTER: "Register",
	VERIFY_PHONE: "VerifyPhone",
	PASSWORD_RESET: "PasswordReset"
});
